services:
  - type: web
    name: finance-tracker
    env: node
    buildCommand: "npm install --prefix server && npm install --prefix client && npm run build --prefix client"
    startCommand: "node server/server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
